repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--django]
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - pyproject-flake8
          - radon

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-aiofiles

  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        args:
          - --check
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args:
          - --check-only
        additional_dependencies:
          - toml

  - repo: local
    hooks:
      - id: unit-test
        language: system
        name: unit test
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [commit]
